# Generated by Django 6.1 on 2026-08-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='ID чата пользователя в Телеграм для отправки уведомлений', max_length=100, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
