# Generated by Django 6.1 on 2026-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_tg_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID чата пользователя в Телеграм для отправки уведомлений', max_length=100, verbose_name='Telegram Chat ID'),
            preserve_default=False,
        ),
    ]
