# Generated by Django 6.1 on 2026-08-26 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Место, где должна выполняться привычка', max_length=100, null=True, verbose_name='Место')),
                ('time_at', models.TimeField(blank=True, help_text='Время, когда нужно выполнить привычку', null=True, verbose_name='Время')),
                ('action', models.CharField(help_text='Действие, которое нужно выполнить', max_length=100, verbose_name='Действие')),
                ('sign_pleasant_habit', models.BooleanField(default=False, help_text='Укажите: либо True, либо False', verbose_name='Признак приятности')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Укажите количество дней (по умолчанию 1 день)', verbose_name='Периодичность')),
                ('award', models.CharField(blank=True, help_text='Вознаграждение', max_length=250, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.DurationField(blank=True, help_text='Укажите в формате ЧЧ:ММ:СС', null=True, verbose_name='Время на выполнение')),
                ('is_publicity', models.BooleanField(default=False, help_text='Укажите: либо True, либо False', verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Связанная привычка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='routines.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(help_text='Пользователь, к которому привязана привычка', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
