# Generated by Django 6.1 on 2026-08-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='award',
            field=models.CharField(blank=True, default='', help_text='Вознаграждение', max_length=250, verbose_name='Вознаграждение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Место, где должна выполняться привычка', max_length=100, verbose_name='Место'),
            preserve_default=False,
        ),
    ]
