# Generated by Django 6.1 on 2026-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_alter_habit_award_alter_habit_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('id',), 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AddField(
            model_name='habit',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='ID чата пользователя в Телеграм для отправки уведомлений', max_length=100, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
