# Generated by Django 6.1 on 2026-08-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_alter_habit_options_habit_tg_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='tg_chat_id',
        ),
    ]
