# Generated by Django 6.1 on 2026-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0004_remove_habit_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_sent_date',
            field=models.DateField(blank=True, help_text='Заполняется автоматически при успешной отправке уведомления в Telegram', null=True, verbose_name='Дата последней отправки'),
        ),
    ]
