version: '3.8'

services:
  web:
    build: .
    container_name: kaisen_django
    restart: no
    env_file:
      - .env
    # Вместо ports используем expose, чтобы порт 8000 был виден ТОЛЬКО для Nginx
    expose:
      - "8000"
    volumes:
      - .:/code
      - /code/.venv # Экранируем папку от перезаписи
      - static_volume:/code/static
    # На виртуалке замените эту строку на запуск gunicorn:
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:1.25-alpine
    container_name: kaisen-nginx
    restart: no
    ports:
      - "80:80" # Открываем стандартный web-порт наружу
    volumes:
      # Пробрасываем конфигурационный файл
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Монтируем статику в стандартную для Nginx папку (измените путь в nginx.conf, см. ниже)
      - static_volume:/var/html/static:ro
    depends_on:
      - web
  
  celery:
    build: .
    container_name: kaisen_celery
    restart: no
    env_file:
      - .env
    volumes:
      - .:/code
      - /code/.venv
    command: celery -A config worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery-beat:
    build: .
    container_name: kaisen_celery_beat
    restart: no
    env_file:
      - .env
    volumes:
      - .:/code
      - /code/.venv
    command: celery -A config beat --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:16-alpine
    container_name: kaisen_postgres
    restart: no
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: kaisen_redis
    restart: no
    # Убрали порты наружу для безопасности
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  static_volume:
