upstream django_app {
    # Имя сервиса из docker-compose и его внутренний порт
    server kaisen_django:8000;
}

server {
    listen 80;
    server_name localhost; # Когда появится домен, нужно заменить localhost на mysite.com

    # Максимальный размер загружаемых файлов (например, картинок в медиа)
    client_max_body_size 20M;

    # Раздача статики Django
    location /static/ {
        alias /var/html/static/;
    }

    # Перенаправление всех остальных запросов на Gunicorn
    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
